### ISSUE TITLE
Allow dialog/modal to be open by default on connect

### ISSUE THREAD

**Issue by Jordybastien** [PhlexUI/phlex_ui_stimulus#9]
This is just a follow-up to this issue that was recently closed https://github.com/PhlexUI/phlex_ui_stimulus/issues/7

I guess I did not provide precise information, I was hoping to have it fixed in the Modal component https://github.com/PhlexUI/phlex_ui_stimulus/blob/main/controllers/dialog_controller.js

**Comment by iseth** [comment]
Ohh yeah missed that. If you open a pr i can review it and merge it 👍

**Comment by Jordybastien** [comment]
I wish I could, but I do not have permission to push to this repository @iseth

**Comment by Jordybastien** [comment]
[Link to PR here](https://github.com/PhlexUI/phlex_ui_stimulus/pull/10) @iseth
